name: mocdart
version: 0.0.1
author: Moctis
description: A sample angular application
homepage: http://mocdart.appspot.com/

dependencies:
  logging: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
