application: mocdart
version: 2
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: 1s

handlers:
# Handler for the main page
- url: /
  static_files : index.html
  upload: build/web/index.html      

- url: /(.*\.(html|js|png|css|dart|json))
  static_files: \1
  upload: build/web/(.*\.(html|js|png|css|dart|json))
  secure: never
  
libraries:
- name: webapp2
  version: "2.5.2"
