application: mocdart
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Handler for the main page
- url: /
  static_files : build/index.html
  upload: build/index.html
  
- url: /css
  static_dir: build/css
  
- url: /images
  static_dir: build/images

# Handler for rooms
- url: /room
  static_files : web/room.html
  upload: web/room.html

# Handler for the main script
- url: /index.dart
  mime_type: application/dart
  static_files: web/index.dart
  upload: web/index.dart

# Handlers to get rid of .dart file mime type warnings when uploading
- url: /style/(.*\.dart)
  mime_type: application/dart
  static_files: web/style/\1
  upload: web/style/(.*\.dart)

- url: /packages/(.*\.dart)
  mime_type: application/dart
  static_files: packages/\1
  upload: packages/(.*\.dart)

- url: /components/(.*\.dart)
  mime_type: application/dart
  static_files: web/components/\1
  upload: web/components/(.*\.dart)

# Handler for CSS files
- url: /style
  static_dir: web/style

# Handler for dart packages
- url: /packages
  static_dir: packages

# Handler for my custom components
- url: /components
  static_dir: web/components
  
  
libraries:
- name: webapp2
  version: "2.5.2"
