application: mocdart
version: 2
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: 1s

handlers:
# Handler for the main page
- url: /
  static_files : index.html
  upload: build/web/index.html      

- url: /(.*\.js)
  static_files: build/web/\1
  upload: build/web/(.*\.js)
  
- url: /packages
  static_dir: build/web/packages

  
libraries:
- name: webapp2
  version: "2.5.2"
