application: mocdart
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: never

- url: /
  static_files: build/web/index.html
  upload: build/web/index.html
  secure: never

#- url: /nossl.appcache
#  static_files: nossl.appcache
#  upload: nossl.appcache
#  secure: never

- url: /(.*\.(html|js|png|css|dart|json|html_reference))
  static_files: build/web/\1
  upload: build/web/(.*\.(html|js|png|css|dart|json|html_reference))
  secure: never

#- url: /css/fonts/fontawesome-webfont.woff
#  static_files: fontawesome-webfont.woff
#  upload: fontawesome-webfont.woff
#  secure: never

- url: .*
  static_files: not_found.html
  upload: not_found.html
  secure: never

libraries:
- name: webapp2
  version: "2.5.2"