application: mocdart
version: 3
runtime: python27
api_version: 1
threadsafe: yes
dart2js: true

handlers:
# Handler for the main page
- url: /
  static_files : build/web/index.html
  upload: build/web/index.html
  
- url: /(.*\.html)
  static_files: build/web/\1
  upload: build/web/(.*\.html)
    
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: build/web/\1
  upload: build/web/(.*\.js)
  
- url: /(.*\.map)
  mime_type: application/octet-stream
  static_files: build/web/\1
  upload: build/web/(.*\.map)
  

# Handlers to get rid of .dart file mime type warnings when uploading
- url: /(.*\.dart)
  mime_type: application/dart
  static_files: build/web/\1
  upload: build/web/(.*\.dart)

- url: /packages/(.*\.dart)
  mime_type: application/dart
  static_files: web/packages/\1
  upload: build/web/packages/(.*\.dart)

# Handler for dart packages
- url: /packages
  static_dir: build/web/packages

- url: /css
  static_dir: build/web/css 

# Handler for libraries
#- url: /components
  #static_dir: client/lib/components

#- url: /services
 # static_dir: client/lib/services

#- url: /models
  #static_dir: client/lib/models

# All other requests are handled by the Go code
- url: /
  static_files: build/web/index.html
  upload: build/web/index.html