application: mocdart
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: web/index.html
  upload: web/index.html

- url: /(.*)
  static_files: web/\1
  upload: web/(.*)

- url: /images/(.*\.(jpg)))
  static_files: web/images/\1
  upload: web/images/(.*\.(jpg))
  
- url: /css/(.*\.css)
  static_files: web/css/\1
  upload: web/css/(.*\.css)
  
  
  
libraries:
- name: webapp2
  version: "2.5.2"
