application: mocdart
version: 2
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: 1s

handlers:
# Handler for the main page

- url: /packages/(.*\.dart)
  mime_type: application/dart
  static_files: build/client/packages/\1
  upload: build/client/packages/(.*\.dart)
    
- url: /packages
  static_dir: build/client/packages

- url: /(.*\.dart)
  mime_type: application/dart
  static_files: build/client/\1
  upload: build/client/(.*\.dart)

- url: /(.*\.(js|html|html_reference|map))
  static_files: build/client/\1
  upload: build/client/(.*\.(js|html|html_reference|map))
  
- url: /
  static_files : build/client/index.html
  upload: build/client/index.html      
  
