name: mocdart
version: 0.0.1
author: Moctis
description: A sample application
homepage: http://mocdart.appspot.com/
dependencies:
  angular: any
  browser: any
transformers:
- less_node:
    entry_point: web/builder.less
