name: MocDart
description: A sample Polymer application
dependencies:
  angular:
    git:
      url: https://github.com/angular/angular.dart.git
  bootjack: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
